"""Identifiers for objects on the CAN bus(es) and physical robot dimensions.

Note: Swerve drivetrain configuration is now in generated/tuner_constants.py
which is designed to be regenerated by Phoenix Tuner X's Swerve Project Generator.
"""

from enum import IntEnum
from typing import Final

import wpilib
import wpimath.geometry as geo
import wpimath.units as units

# Associate alliances with the field-centric rotation that is forward.
ALLIANCE_PERSPECTIVE_ROTATION: dict[wpilib.DriverStation.Alliance, geo.Rotation2d] = {
    wpilib.DriverStation.Alliance.kBlue: geo.Rotation2d.fromDegrees(0),
    wpilib.DriverStation.Alliance.kRed: geo.Rotation2d.fromDegrees(180),
}


class CANID(IntEnum):
    """IDs for items on the CAN bus.

    Note: Swerve motor and encoder CAN IDs are now in generated/tuner_constants.py.
    """

    # Other motors (non-swerve)
    SHOOTER_MOTOR_TOP = 15
    SHOOTER_MOTOR_BOTTOM = 16
    FEEDER_MOTOR = 17

    SHOOTER_MOTOR_TOP_CANCODER = 18
    SHOOTER_MOTOR_BOTTOM_CANCODER = 19


class RobotDimension:
    """Physical dimensions and locations of robot components.

    Note: Swerve module locations are now in generated/tuner_constants.py.
    """

    # Shooter dimensions
    SHOOTER_Z: Final[units.meters] = 0.421
    SHOOTER_MAX_ANGLE: Final[units.radians] = units.degreesToRadians(34.0)


class ControllerPort:
    """USB ports for controllers."""

    DRIVER_CONTROLLER: Final[int] = 0
    OPERATOR_CONTROLLER: Final[int] = 1
